_wandb:
    value:
        cli_version: 0.23.1
        e:
            vmyurr7nespt23yuls1ddupvptu925sk:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "8589934592"
                args:
                    - --batch_size=8
                    - --beta1=0.9
                    - --beta2=0.999
                    - --checkpoint_dir=/Users/shawnspitzel/cs336/cs326/assignment1-basics/cs336_basics/checkpoints/model/gpt4-small-tinystories
                    - --checkpoint_interval=1000
                    - --compile=False
                    - --context_length=256
                    - --cosine_iters=100000
                    - --d_ff=1024
                    - --d_model=256
                    - --data_dtype=uint16
                    - --device=cpu
                    - --eval_interval=500
                    - --eval_iters=100
                    - --gradient_clip_norm=1
                    - --learning_rate=0.0003
                    - --log_interval=100
                    - --max_iters=1500
                    - --min_lr=6e-05
                    - --num_heads=4
                    - --num_layers=4
                    - --optimizer=adamw
                    - --resume_from=None
                    - --seed=42
                    - --theta=10000
                    - --train_data=/Users/shawnspitzel/cs336/cs326/assignment1-basics/cs336_basics/data/tokenized/tinystories/train/TinyStoriesV2-GPT4-train_tokens_.bin
                    - --val_data=/Users/shawnspitzel/cs336/cs326/assignment1-basics/cs336_basics/data/tokenized/tinystories/val/TinyStoriesV2-GPT4-valid_val_tokens_.bin
                    - --vocab_size=100000
                    - --warmup_iters=2000
                    - --weight_decay=0.01
                codePath: assignment1-basics/cs336_basics/training/pretrain.py
                codePathLocal: assignment1-basics/cs336_basics/training/pretrain.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "224750104576"
                email: shawnspitzel@gmail.com
                executable: /Users/shawnspitzel/cs336/cs326/assignment1-basics/.venv/bin/python
                git:
                    commit: 27cc478c80fb62a69c2c241c72f749480b127653
                    remote: https://github.com/shawnspitzel/cs326.git
                host: Shawns-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-13.4.1-arm64-arm-64bit
                program: /Users/shawnspitzel/cs336/cs326/assignment1-basics/cs336_basics/training/pretrain.py
                python: CPython 3.12.7
                root: /Users/shawnspitzel/cs336/cs326
                startedAt: "2026-01-02T23:07:35.880638Z"
                writerId: vmyurr7nespt23yuls1ddupvptu925sk
        m:
            - "1": iteration
              "6":
                - 3
              "7": []
            - "2": train/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": val/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 7
                - 13
                - 14
                - 16
            "4": 3.12.7
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 8
beta1:
    value: 0.9
beta2:
    value: 0.999
checkpoint_dir:
    value: /Users/shawnspitzel/cs336/cs326/assignment1-basics/cs336_basics/checkpoints/model/gpt4-small-tinystories
checkpoint_interval:
    value: 1000
compile:
    value: false
context_length:
    value: 256
cosine_iters:
    value: 100000
d_ff:
    value: 1024
d_model:
    value: 256
data_dtype:
    value: uint16
device:
    value: cpu
eval_interval:
    value: 500
eval_iters:
    value: 100
gradient_clip_norm:
    value: 1
learning_rate:
    value: 0.0003
log_interval:
    value: 100
max_iters:
    value: 1500
min_lr:
    value: 6e-05
num_heads:
    value: 4
num_layers:
    value: 4
optimizer:
    value: adamw
profile:
    value: false
profile_output:
    value: checkpoints/profile_stats.prof
resume_from:
    value: null
seed:
    value: 42
theta:
    value: 10000
train_data:
    value: /Users/shawnspitzel/cs336/cs326/assignment1-basics/cs336_basics/data/tokenized/tinystories/train/TinyStoriesV2-GPT4-train_tokens_.bin
use_params:
    value: false
use_wandb:
    value: false
val_data:
    value: /Users/shawnspitzel/cs336/cs326/assignment1-basics/cs336_basics/data/tokenized/tinystories/val/TinyStoriesV2-GPT4-valid_val_tokens_.bin
vocab_size:
    value: 100000
wandb_project:
    value: cs336-assignment1
wandb_run_name:
    value: null
warmup_iters:
    value: 2000
weight_decay:
    value: 0.01
