program: src/training/pretrain.py
project: AtlasLM-Pretrain-GPT2-Tiny
method: grid
metric:
  name: val/loss
  goal: minimize

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}

parameters:
  d_model:
    value: 640
  num_heads:
    value: 10
  d_ff:
    value: 2560
  num_layers:
    value: 10
  vocab_size:
    value: 50257
  context_length:
    value: 512
  theta:
    value: 10000.0

  batch_size:
    value: 8
  max_iters:
    value: 10000
  eval_interval:
    value: 500
  eval_iters:
    value: 20
  log_interval:
    value: 10
  checkpoint_interval:
    value: 5000
  seed:
    value: 42

  optimizer:
    value: adamw
  learning_rate:
    value: 6.0e-4
  min_lr:
    value: 6.0e-5
  weight_decay:
    value: 0.1
  beta1:
    value: 0.9
  beta2:
    value: 0.95
  gradient_clip_norm:
    value: 1.0

  warmup_iters:
    value: 2000
  cosine_iters:
    value: 80000

  train_data:
    value: src/data/tokenized/owt/train/owt_train_tokens_.bin
  val_data:
    value: src/data/tokenized/owt/val/owt_valid_val_tokens_.bin
  data_dtype:
    value: uint16

  checkpoint_dir:
    value: src/checkpoints/model/gpt2-tiny

  resume_from:
    value: null

  device:
    value: cuda
  compile:
    value: true
